Repository Sidrti/rec, pull requests merged in 2020-12, with the labels that each got.

#11 Move Account File Changes
  app/Http/Controllers/AccountListController.php
  app/Http/Controllers/api_info_controller.php
  app/Http/Controllers/api_trail_list.php
  app/Http/Controllers/move_account.php
  public/css/move_account.css
  resources/views/api_info.blade.php
  resources/views/header.blade.php
  resources/views/move_account.blade.php
  routes/web.php
Labels: enhancement

#12 !IMPORTANT Refactoring the whole project code - Hotfix
  app/Http/Controllers/AccountListController.php
  app/Http/Controllers/FailSwitchDetailController.php
  app/Http/Controllers/InsertUserDetails.php
  app/Http/Controllers/PackageMasterController.php
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/RoleMasterController.php
  app/Http/Controllers/TblAmountFilterController.php
  app/Http/Controllers/TblMyOperatorController.php
  app/Http/Controllers/TestController.php
  app/Http/Controllers/UserController.php
  app/Http/Controllers/add_api_controller.php
  app/Http/Controllers/add_sms_api.php
  app/Http/Controllers/api_info_controller.php
  app/Http/Controllers/api_trail_list.php
  app/Http/Controllers/news.php
  app/Http/Controllers/sms_api_controller.php
  app/Http/Controllers/user_detail.php
  app/Http/Controllers/view_api_controller.php
  public/css/account_list.css
  public/css/api_trail.css
  public/css/header.css
  public/css/move_account.css
  public/css/news.css
  public/css/operator_list.css
  resources/views/API_Trail.blade.php
  resources/views/News.blade.php
  resources/views/account_list.blade.php
  resources/views/amount_filter.blade.php
  resources/views/api_info.blade.php
  resources/views/failed_switch.blade.php
  resources/views/header.blade.php
  resources/views/move_account.blade.php
  resources/views/navigation-dropdown.blade.php
  resources/views/operatorlist.blade.php
  resources/views/package_master.blade.php
  resources/views/sms_api.blade.php
  resources/views/view_api.blade.php
  routes/web.php
Labels: documentation, enhancement

#14 Transfer Stock Account List
  app/Http/Controllers/AccountListController.php
  app/Models/balance.php
  app/Models/ledger.php
  public/css/account_list.css
  resources/views/API_Trail.blade.php
  resources/views/account_list.blade.php
  resources/views/getdata.blade.php
  routes/web.php
Labels: documentation, enhancement

#15 Filters Added in Account list
  public/js/jquery.table-filterable-min.js
  public/js/jquery.table-filterable.js
  resources/views/account_list.blade.php
Labels: enhancement

#16 Account List Credit Modal
  app/Http/Controllers/AccountListController.php
  resources/views/account_list.blade.php
  resources/views/getdata_credit.blade.php
  routes/web.php
Labels: documentation, enhancement

#18 Account list credit
  app/Http/Controllers/AccountListController.php
  app/Models/receive_credit.php
  auth1.sql
  resources/views/account_list.blade.php
  routes/web.php
Labels: enhancement

#19 Account Capping Functionality Added
  app/Http/Controllers/AccountCappingController.php
  app/Models/tbl_capping.php
  app/Models/tbl_capping_detail.php
  public/css/account_list.css
  resources/views/account_capping.blade.php
  resources/views/header.blade.php
  resources/views/operatorlist.blade.php
  routes/web.php
Labels: Need Review, enhancement

#20 ADD Bank Account in Payment Req
  app/Http/Controllers/AddBankAccountController.php
  app/Http/Controllers/MyBankAccountController.php
  app/Models/tbl_add_bank_account.php
  app/Models/tbl_my_bank_account.php
  resources/views/account_capping.blade.php
  resources/views/header.blade.php
  resources/views/my_bank_account.blade.php
  routes/web.php
Labels: enhancement

#21 Quick fix in Data Table
  resources/views/account_capping.blade.php
  resources/views/account_list.blade.php
  resources/views/operatorlist.blade.php
Labels: bug resolved

#22 HotFix for deployment important
  app/Http/Controllers/AccountCappingController.php
  app/Http/Controllers/AccountListController.php
  app/Http/Controllers/PackageMasterController.php
  app/Http/Controllers/TblMyOperatorController.php
  resources/views/account_capping.blade.php
  resources/views/account_list.blade.php
  resources/views/operatorlist.blade.php
  resources/views/package_master.blade.php
Labels: documentation, enhancement

#23 Operator list issue
  app/Http/Controllers/MyBankAccountController.php
  resources/views/my_bank_account.blade.php
  resources/views/operatorlist.blade.php
Labels: bug resolved, enhancement

#24 FTP fixes remianing
  app/Http/Controllers/api_info_controller.php
  app/Http/Controllers/header.php
  resources/views/header.blade.php
  resources/views/move_account.blade.php
  resources/views/welcome.blade.php
Labels: bug resolved

#25 API Trail Remove Edit Button
  resources/views/API_Trail.blade.php
  routes/web.php
Labels: documentation

#26 Fail Switch Issue fixed
  app/Http/Controllers/api_trail_list.php
  resources/views/API_Trail.blade.php
  resources/views/failed_switch.blade.php
  routes/web.php
Labels: bug resolved

#29 API Trail List dropdown issue
  resources/views/API_Trail.blade.php
Labels: bug resolved

#30 PackageDetailsFiles
  api_info_controller.php
  app/Http/Controllers/api_trail_list.php
  app/Http/Controllers/packagedetailsController.php
  app/Models/package_list.php
  resources/views/API_Trail.blade.php
  resources/views/failed_switch.blade.php
  resources/views/package_details.blade.php
  resources/views/package_master.blade.php
  routes/web.php
Labels: enhancement

#31 Fixes of Account List & Account Capping for deployment
  app/Http/Controllers/AccountListController.php
  public/css/account_list.css
  public/css/api_trail.css
  resources/views/API_Trail.blade.php
  resources/views/account_capping.blade.php
  resources/views/account_list.blade.php
  resources/views/getdata.blade.php
Labels: bug resolved

#32 API Codes updation & Insertion Functionality added
  app/Http/Controllers/api_info_controller.php
  resources/views/api_info.blade.php
Labels: bug resolved, enhancement

#33 Updated DB 21 December
  auth1.sql
Labels: documentation

#34 Default Package Functionality Added
  app/Http/Controllers/DefaultPackageController.php
  app/Models/default_package.php
  public/css/account_list.css
  resources/views/default_package.blade.php
  resources/views/header.blade.php
  resources/views/package_master.blade.php
  routes/web.php
Labels: documentation, enhancement

#35 Package List model added with functionality
  app/Http/Controllers/packagedetailsController.php
  public/css/account_list.css
  public/css/api_trail.css
  public/css/news.css
  public/css/operator_list.css
  resources/views/api_info.blade.php
  resources/views/package_details.blade.php
  resources/views/package_master.blade.php
  routes/web.php
Labels: bug resolved, enhancement

#36 Issues Fixed, Default Package ISSue
  app/Http/Controllers/DefaultPackageController.php
  public/css/account_list.css
  public/css/header.css
  resources/views/account_list.blade.php
  resources/views/api_info.blade.php
Labels: bug resolved

#38 Account list one filter added and lock icon functionality
  app/Http/Controllers/AccountListController.php
  public/css/account_list.css
  resources/views/account_capping.blade.php
  resources/views/account_list.blade.php
  routes/web.php
Labels: enhancement

#40 Recharge List Functionality Added
  app/Http/Controllers/AccountCappingController.php
  app/Http/Controllers/AccountListController.php
  app/Http/Controllers/RechargeListController.php
  public/css/recharge_list.css
  resources/views/account_capping.blade.php
  resources/views/account_list.blade.php
  resources/views/header.blade.php
  resources/views/recharge_list.blade.php
  routes/web.php
Labels: documentation, enhancement

#41 AccounList & RechargeList Fixes
  app/Http/Controllers/AccountListController.php
  public/css/recharge_list.css
  resources/views/API_Trail.blade.php
  resources/views/account_list.blade.php
  resources/views/recharge_list.blade.php
  routes/web.php
Labels: bug resolved

#42 Header Enhancement and other issues
  app/Http/Controllers/api_trail_list.php
  public/css/header.css
  public/images/logo.png
  public/images/user.svg
  public/images/wallet.svg
  resources/views/API_Trail.blade.php
  resources/views/header.blade.php
  resources/views/package_master.blade.php
Labels: bug resolved, documentation, enhancement

#45 AmountFilterChanges
  app/Http/Controllers/TblAmountFilterController.php
  resources/views/amount_filter.blade.php
Labels: enhancement

#46 Remove Extra files
  api_info_controller.php
  api_trail_list.php
Labels: duplicate

#47 Add New API functionality in fail switching
  app/Http/Controllers/api_trail_list.php
  resources/views/API_Trail.blade.php
  routes/web.php
Labels: enhancement
